### ISSUE TITLE
צבע שורת המשימות

### ISSUE THREAD

**Issue by ori-halevi** [matipojo/baafucha#1]
לפי מה שכתבת בלינקדאון הנחתי שצבע שורת המשימות ישתנה בהתאם אל השפה...
אולי זה קצת מורכב אבל זה אפשרי, אני הצלחתי לעשות התקדמות בנושא הזה אבל בצורה מאד "חפיפה".
אשמח לשמוע ממך

**Comment by ori-halevi** [comment]
https://github.com/user-attachments/assets/f55b9434-db83-400b-80b9-b45064171610

**Comment by matipojo** [comment]
Thanks! Please send a PR 🙏
